/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 16-feb.-2023 20:48:04 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Articulo_Marca]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Articulo] DROP CONSTRAINT [FK_Articulo_Marca]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Articulo_UnidadMedida]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Articulo] DROP CONSTRAINT [FK_Articulo_UnidadMedida]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Articulo_DetalleCompra_Articulo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Articulo_DetalleCompra] DROP CONSTRAINT [FK_Articulo_DetalleCompra_Articulo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Articulo_DetalleCompra_DetalleCompra]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Articulo_DetalleCompra] DROP CONSTRAINT [FK_Articulo_DetalleCompra_DetalleCompra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Articulo_DetalleVenta_Articulo]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Articulo_DetalleVenta] DROP CONSTRAINT [FK_Articulo_DetalleVenta_Articulo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Articulo_DetalleVenta_DetalleVenta]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Articulo_DetalleVenta] DROP CONSTRAINT [FK_Articulo_DetalleVenta_DetalleVenta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cliente_Persona]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cliente] DROP CONSTRAINT [FK_Cliente_Persona]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Compra_Proveedor]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Compra] DROP CONSTRAINT [FK_Compra_Proveedor]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DetalleCompra_Compra]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DetalleCompra] DROP CONSTRAINT [FK_DetalleCompra_Compra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_DetalleVenta_Venta]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [DetalleVenta] DROP CONSTRAINT [FK_DetalleVenta_Venta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Empleado_Persona]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Empleado] DROP CONSTRAINT [FK_Empleado_Persona]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Empleado_Rol]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Empleado] DROP CONSTRAINT [FK_Empleado_Rol]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Localidad_Provinicia]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Localidad] DROP CONSTRAINT [FK_Localidad_Provinicia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Marca_Proveedor_Marca]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Marca_Proveedor] DROP CONSTRAINT [FK_Marca_Proveedor_Marca]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Marca_Proveedor_Proveedor]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Marca_Proveedor] DROP CONSTRAINT [FK_Marca_Proveedor_Proveedor]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Proveedor_Localidad]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Proveedor] DROP CONSTRAINT [FK_Proveedor_Localidad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Venta_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Venta] DROP CONSTRAINT [FK_Venta_Cliente]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Articulo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Articulo]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Articulo_DetalleCompra]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Articulo_DetalleCompra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Articulo_DetalleVenta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Articulo_DetalleVenta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Compra]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Compra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DetalleCompra]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DetalleCompra]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[DetalleVenta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [DetalleVenta]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Empleado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Empleado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Localidad]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Localidad]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Marca]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Marca]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Marca_Proveedor]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Marca_Proveedor]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Persona]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Persona]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Proveedor]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Proveedor]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Provinicia]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Provinicia]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Rol]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Rol]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[UnidadMedida]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [UnidadMedida]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Venta]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Venta]
GO

/* Create Tables */

CREATE TABLE [Articulo]
(
	[articulo_id] int NOT NULL IDENTITY (0, 1),
	[nombre] varchar(255) NULL,
	[marca_id] int NULL,
	[cantidadDisponible] int NULL,
	[costoCompra] decimal(18) NULL,
	[precioPorUnidad] decimal(18) NULL,
	[unidadmedida_id] int NULL,
	[minimaCantidadStock] int NULL
)
GO

CREATE TABLE [Articulo_DetalleCompra]
(
	[articulo_id] int NULL,
	[detallecompra_id] int NULL
)
GO

CREATE TABLE [Articulo_DetalleVenta]
(
	[detalleventa_id] int NULL,
	[articulo_id] int NULL
)
GO

CREATE TABLE [Cliente]
(
	[cliente_id] int NOT NULL IDENTITY (0, 1),
	[nroCliente] int NULL,
	[localidad_id] int NULL,
	[persona_id] int NULL
)
GO

CREATE TABLE [Compra]
(
	[compra_id] int NOT NULL IDENTITY (0, 1),
	[proveedor_id] int NULL,
	[fechaCompra] date NULL,
	[montoTotalCompra] decimal(18) NULL
)
GO

CREATE TABLE [DetalleCompra]
(
	[detallecompra_id] int NOT NULL IDENTITY (0, 1),
	[articulo_id] int NULL,
	[cantidadComprada] decimal(18) NULL,
	[compra_id] int NULL
)
GO

CREATE TABLE [DetalleVenta]
(
	[detalleventa_id] int NOT NULL IDENTITY (0, 1),
	[cantidadVendida] decimal(18) NULL,
	[venta_id] int NULL
)
GO

CREATE TABLE [Empleado]
(
	[empleado_id] int NOT NULL IDENTITY (0, 1),
	[legajo] int NULL,
	[fechaIngreso] date NULL,
	[rol_id] int NULL,
	[persona_id] int NULL
)
GO

CREATE TABLE [Localidad]
(
	[localidad_id] int NOT NULL IDENTITY (0, 1),
	[nombre] varchar(255) NULL,
	[provincia_id] int NULL
)
GO

CREATE TABLE [Marca]
(
	[marca_id] int NOT NULL IDENTITY (0, 1),
	[nombre] varchar(255) NULL,
	[descripcion] varchar(255) NULL,
	[porcentajeGanancia] decimal(18) NULL,
	[proveedor_id] int NULL
)
GO

CREATE TABLE [Marca_Proveedor]
(
	[proveedor_id] int NULL,
	[marca_id] int NULL
)
GO

CREATE TABLE [Persona]
(
	[persona_id] int NOT NULL IDENTITY (0, 1),
	[nombre] varchar(255) NULL,
	[apellido] varchar(255) NULL,
	[direccion] varchar(255) NULL,
	[dni] int NULL,
	[fechaNacimiento] date NULL,
	[numeroTelefono] int NULL
)
GO

CREATE TABLE [Proveedor]
(
	[proveedor_id] int NOT NULL IDENTITY (0, 1),
	[nombre] varchar(255) NULL,
	[direccion] varchar(255) NULL,
	[razonSocial] varchar(255) NULL,
	[localidad_id] int NULL
)
GO

CREATE TABLE [Provinicia]
(
	[provincia_id] int NOT NULL IDENTITY (0, 1),
	[nombre] varchar(255) NULL
)
GO

CREATE TABLE [Rol]
(
	[rol_id] int NOT NULL IDENTITY (0, 1),
	[nombre] varchar(255) NULL,
	[descripcion] varchar(255) NULL
)
GO

CREATE TABLE [UnidadMedida]
(
	[unidadmedida_id] int NOT NULL IDENTITY (0, 1),
	[nombre] varchar(255) NULL,
	[descripcion] varchar(255) NULL
)
GO

CREATE TABLE [Venta]
(
	[venta_id] int NOT NULL IDENTITY (0, 1),
	[cliente_id] int NULL,
	[fechaVenta] date NULL,
	[montoTotalVenta] decimal(18) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Articulo] 
 ADD CONSTRAINT [PK_Articulo]
	PRIMARY KEY CLUSTERED ([articulo_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Articulo_Marca] 
 ON [Articulo] ([marca_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Articulo_UnidadMedida] 
 ON [Articulo] ([unidadmedida_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Articulo_DetalleCompra_Articulo] 
 ON [Articulo_DetalleCompra] ([articulo_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Articulo_DetalleCompra_DetalleCompra] 
 ON [Articulo_DetalleCompra] ([detallecompra_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Articulo_DetalleVenta_Articulo] 
 ON [Articulo_DetalleVenta] ([articulo_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Articulo_DetalleVenta_DetalleVenta] 
 ON [Articulo_DetalleVenta] ([detalleventa_id] ASC)
GO

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([cliente_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Cliente_Persona] 
 ON [Cliente] ([persona_id] ASC)
GO

ALTER TABLE [Compra] 
 ADD CONSTRAINT [PK_Compra]
	PRIMARY KEY CLUSTERED ([compra_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Compra_Proveedor] 
 ON [Compra] ([proveedor_id] ASC)
GO

ALTER TABLE [DetalleCompra] 
 ADD CONSTRAINT [PK_DetalleCompra]
	PRIMARY KEY CLUSTERED ([detallecompra_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_DetalleCompra_Compra] 
 ON [DetalleCompra] ([compra_id] ASC)
GO

ALTER TABLE [DetalleVenta] 
 ADD CONSTRAINT [PK_DetalleVenta]
	PRIMARY KEY CLUSTERED ([detalleventa_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_DetalleVenta_Venta] 
 ON [DetalleVenta] ([venta_id] ASC)
GO

ALTER TABLE [Empleado] 
 ADD CONSTRAINT [PK_Empleado]
	PRIMARY KEY CLUSTERED ([empleado_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Empleado_Persona] 
 ON [Empleado] ([persona_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Empleado_Rol] 
 ON [Empleado] ([rol_id] ASC)
GO

ALTER TABLE [Localidad] 
 ADD CONSTRAINT [PK_Localidad]
	PRIMARY KEY CLUSTERED ([localidad_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Localidad_Provinicia] 
 ON [Localidad] ([provincia_id] ASC)
GO

ALTER TABLE [Marca] 
 ADD CONSTRAINT [PK_Marca]
	PRIMARY KEY CLUSTERED ([marca_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Marca_Proveedor_Marca] 
 ON [Marca_Proveedor] ([marca_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Marca_Proveedor_Proveedor] 
 ON [Marca_Proveedor] ([proveedor_id] ASC)
GO

ALTER TABLE [Persona] 
 ADD CONSTRAINT [PK_Persona]
	PRIMARY KEY CLUSTERED ([persona_id] ASC)
GO

ALTER TABLE [Proveedor] 
 ADD CONSTRAINT [PK_Proveedor]
	PRIMARY KEY CLUSTERED ([proveedor_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Proveedor_Localidad] 
 ON [Proveedor] ([localidad_id] ASC)
GO

ALTER TABLE [Provinicia] 
 ADD CONSTRAINT [PK_Provinicia]
	PRIMARY KEY CLUSTERED ([provincia_id] ASC)
GO

ALTER TABLE [Rol] 
 ADD CONSTRAINT [PK_Rol]
	PRIMARY KEY CLUSTERED ([rol_id] ASC)
GO

ALTER TABLE [UnidadMedida] 
 ADD CONSTRAINT [PK_UnidadMedida]
	PRIMARY KEY CLUSTERED ([unidadmedida_id] ASC)
GO

ALTER TABLE [Venta] 
 ADD CONSTRAINT [PK_Venta]
	PRIMARY KEY CLUSTERED ([venta_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Venta_Cliente] 
 ON [Venta] ([cliente_id] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Articulo] ADD CONSTRAINT [FK_Articulo_Marca]
	FOREIGN KEY ([marca_id]) REFERENCES [Marca] ([marca_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Articulo] ADD CONSTRAINT [FK_Articulo_UnidadMedida]
	FOREIGN KEY ([unidadmedida_id]) REFERENCES [UnidadMedida] ([unidadmedida_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Articulo_DetalleCompra] ADD CONSTRAINT [FK_Articulo_DetalleCompra_Articulo]
	FOREIGN KEY ([articulo_id]) REFERENCES [Articulo] ([articulo_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Articulo_DetalleCompra] ADD CONSTRAINT [FK_Articulo_DetalleCompra_DetalleCompra]
	FOREIGN KEY ([detallecompra_id]) REFERENCES [DetalleCompra] ([detallecompra_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Articulo_DetalleVenta] ADD CONSTRAINT [FK_Articulo_DetalleVenta_Articulo]
	FOREIGN KEY ([articulo_id]) REFERENCES [Articulo] ([articulo_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Articulo_DetalleVenta] ADD CONSTRAINT [FK_Articulo_DetalleVenta_DetalleVenta]
	FOREIGN KEY ([detalleventa_id]) REFERENCES [DetalleVenta] ([detalleventa_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Cliente] ADD CONSTRAINT [FK_Cliente_Persona]
	FOREIGN KEY ([persona_id]) REFERENCES [Persona] ([persona_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Compra] ADD CONSTRAINT [FK_Compra_Proveedor]
	FOREIGN KEY ([proveedor_id]) REFERENCES [Proveedor] ([proveedor_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DetalleCompra] ADD CONSTRAINT [FK_DetalleCompra_Compra]
	FOREIGN KEY ([compra_id]) REFERENCES [Compra] ([compra_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [DetalleVenta] ADD CONSTRAINT [FK_DetalleVenta_Venta]
	FOREIGN KEY ([venta_id]) REFERENCES [Venta] ([venta_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Empleado] ADD CONSTRAINT [FK_Empleado_Persona]
	FOREIGN KEY ([persona_id]) REFERENCES [Persona] ([persona_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Empleado] ADD CONSTRAINT [FK_Empleado_Rol]
	FOREIGN KEY ([rol_id]) REFERENCES [Rol] ([rol_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Localidad] ADD CONSTRAINT [FK_Localidad_Provinicia]
	FOREIGN KEY ([provincia_id]) REFERENCES [Provinicia] ([provincia_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Marca_Proveedor] ADD CONSTRAINT [FK_Marca_Proveedor_Marca]
	FOREIGN KEY ([marca_id]) REFERENCES [Marca] ([marca_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Marca_Proveedor] ADD CONSTRAINT [FK_Marca_Proveedor_Proveedor]
	FOREIGN KEY ([proveedor_id]) REFERENCES [Proveedor] ([proveedor_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Proveedor] ADD CONSTRAINT [FK_Proveedor_Localidad]
	FOREIGN KEY ([localidad_id]) REFERENCES [Localidad] ([localidad_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Venta] ADD CONSTRAINT [FK_Venta_Cliente]
	FOREIGN KEY ([cliente_id]) REFERENCES [Cliente] ([cliente_id]) ON DELETE No Action ON UPDATE No Action
GO
